src/Entity/Invoice.php
<?php

namespace App\Entity;

use App\Repository\InvoiceRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=InvoiceRepository::class)
 */
class Invoice
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $invoice_no;

    /**
     * @ORM\Column(type="date")
     */
    private $invoice_date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $service;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $quantity;

    /**
     * @ORM\Column(type="decimal", precision=15, scale=2)
     */
    private $unit_price;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $currency;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ettn;

    /**
     * @ORM\Column(type="decimal", precision=15, scale=2, nullable=true)
     */
    private $total;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="invoices")
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Company", inversedBy="invoices")
     */
    private $company;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getInvoiceNo()
    {
        return $this->invoice_no;
    }

    public function setInvoiceNo($invoice_no): self
    {
        $this->invoice_no = $invoice_no;

        return $this;
    }

    public function getInvoiceDate()
    {
        return $this->invoice_date;
    }

    /**
     * Set Invoice Date
     *
     * @param \DateTime $invoice_date
     *
     * @return Invoice
     */
    public function setInvoiceDate($invoice_date): self
    {
        $this->invoice_date = $invoice_date;

        return $this;
    }

    public function getService()
    {
        return $this->service;
    }

    public function setService($service): self
    {
        $this->service = $service;

        return $this;
    }

    public function getQuantity()
    {
        return $this->quantity;
    }

    public function setQuantity($quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getUnitPrice()
    {
        return $this->unit_price;
    }

    public function setUnitPrice($unit_price): self
    {
        $this->unit_price = $unit_price;

        return $this;
    }

    public function getCurrency()
    {
        return $this->currency;
    }

    public function setCurrency($currency): self
    {
        $this->currency = $currency;

        return $this;
    }

    public function getEttn()
    {
        return $this->ettn;
    }

    public function setEttn($ettn): void
    {
        $this->ettn = $ettn;
    }

    public function getUser()
    {
        return $this->user;
    }

    public function setUser($user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCompany()
    {
        return $this->company;
    }

    public function setCompany($company): self
    {
        $this->company = $company;

        return $this;
    }

    public function getTotal()
    {
        return $this->total;
    }

    public function setTotal($total): void
    {
        $this->total = $total;
    }
}

src/Form/InvoiceType.php
<?php

namespace App\Form;

use App\Entity\Company;
use App\Entity\Invoice;
use App\Entity\User;
use Doctrine\DBAL\Types\IntegerType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CurrencyType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class InvoiceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('invoice_no', TextType::class)
            ->add('ettn', TextType::class)
            ->add(
                'invoice_date',
                DateType::class,
                [
                    'widget' => 'single_text',
                ]
            )
            ->add('service', TextType::class)
            ->add('quantity', TextType::class)
            ->add('unit_price', MoneyType::class)
            ->add('currency', TextType::class)
            ->add(
                'user',
                EntityType::class,
                [
                    'class' => User::class,
                    'choice_label' => 'name',
                ]
            )
            ->add(
                'company',
                EntityType::class,
                [
                    'class' => Company::class,
                    'choice_label' => 'name',
                ]
            )
            ->add('total', MoneyType::class)
            ->add('submit', SubmitType::class);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            [
                'data_class' => Invoice::class,
            ]
        );
    }
}

src/Controller/InvoiceController.php
<?php

namespace App\Controller;

use App\Entity\Invoice;
use App\Form\InvoiceType;
use App\Repository\InvoiceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class InvoiceController.
 *
 * @Route("/invoice")
 */
class InvoiceController extends AbstractController
{
    /**
     * @var InvoiceRepository
     */
    private $invoiceRepository;

    public function __construct(InvoiceRepository $invoiceRepository)
    {
        $this->invoiceRepository = $invoiceRepository;
    }

    /**
     * @Route("", name="invoice.index", methods={"GET"})
     */
    public function index(): Response
    {
        $invoices = $this->invoiceRepository->findWithCompany();

        return $this->render(
            'invoice/index.html.twig',
            [
                'invoices' => $invoices,
            ]
        );
    }

    /**
     * @Route("/create", name="invoice.create")
     */
    public function create(Request $request): Response
    {
        $invoice = new Invoice();
        $invoice->setCurrency('EUR');
        $form = $this->createForm(
            InvoiceType::class,
            $invoice,
            [
                'action' => $this->generateUrl('invoice.create'),
            ]
        );

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($invoice);
            $em->flush();
        }

        return $this->render(
            'invoice/create.html.twig',
            [
                'invoice_create_form' => $form->createView(),
            ]
        );
    }

    /**
     * @Route("/edit/{id}", name="invoice.edit")
     */
    public function edit(Request $request, $id): Response
    {
        $invoice = $this->invoiceRepository->find($id);
        $form = $this->createForm(
            InvoiceType::class,
            $invoice,
            [
                'action' => $this->generateUrl('invoice.edit', ['id' => $id]),
            ]
        );

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($invoice);
            $em->flush();
        }

        return $this->render(
            'invoice/create.html.twig',
            [
                'invoice_create_form' => $form->createView(),
            ]
        );
    }

    /**
     * @Route("/delete/{id}", name="invoice.delete")
     */
    public function delete($id): Response
    {
        $invoice = $this->invoiceRepository->find($id);

        $em = $this->getDoctrine()->getManager();
        $em->remove($invoice);
        $em->flush();

        return $this->redirectToRoute('invoice.index');
    }

    /**
     * @Route("/show/{id}", name="invoice.show")
     */
    public function show($id): Response
    {
        $invoice = $this->invoiceRepository->find($id);

        return $this->render(
            'invoice/show.html.twig',
            [
                'invoice' => $invoice
            ]
        );
    }



}

templates/invoice/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create User{% endblock %}
{% block body %}
    <a href="{{ path('invoice.index') }}" class="btn btn-primary">Back</a>

    {{ form_start(invoice_create_form, {'attr': {'id': 'create_invoice_form'}}) }}
    {{ form(invoice_create_form) }}
    {{ form_end(invoice_create_form) }}

    <script>
        const unitPriceElement = document.querySelector('#invoice_unit_price');
        const quantityElement = document.querySelector('#invoice_quantity');
        const totalElement = document.querySelector('#invoice_total');

        unitPriceElement.addEventListener('focus', (event) => {
            const unitPriceValue = unitPriceElement.value
            const quantityValue = quantityElement.value.split(' ')[0];
            totalElement.value = parseFloat(unitPriceValue) * parseInt(quantityValue);
        });

        unitPriceElement.addEventListener('blur', (event) => {
            const unitPriceValue = unitPriceElement.value
            const quantityValue = quantityElement.value.split(' ')[0];
            totalElement.value = parseFloat(unitPriceValue) * parseInt(quantityValue);
        });

        unitPriceElement.addEventListener('keyup', (event) => {
            const unitPriceValue = unitPriceElement.value
            const quantityValue = quantityElement.value.split(' ')[0];
            totalElement.value = parseFloat(unitPriceValue) * parseInt(quantityValue);
        });
    </script>
{% endblock %}

templates/invoice/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create User{% endblock %}
{% block body %}
    <a href="{{ path('user.index') }}" class="btn btn-primary">Back</a>

    {{ form_start(user_create_form, {'attr': {'id': 'create_user_form'}}) }}
    {{ form(user_create_form) }}
    {{ form_end(user_create_form) }}
{% endblock %}

templates/invoice/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello UserController!{% endblock %}

{% block body %}
    <a href="{{ path('invoice.create') }}" class="btn btn-primary">Create</a>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Invoice No</th>
            <th scope="col">Company</th>
            <th scope="col">Invoice Date</th>
            <th scope="col">Service</th>
            <th scope="col">Quantity</th>
            <th scope="col">Unit Price</th>
            <th scope="col">Currency</th>
            <th scope="col">Total</th>
        </tr>
        </thead>
        <tbody>
        {% for invoice in invoices %}
            <tr>
                <td>{{ invoice.id }}</td>
                <td>{{ invoice.company ? invoice.company.name }}</td>
                <td>{{ invoice.invoiceNo }}</td>
                <td>{{ invoice.invoiceDate|date("Y-M-d") }}</td>
                <td>{{ invoice.service }}</td>
                <td>{{ invoice.quantity }}</td>
                <td>{{ invoice.unitPrice }}</td>
                <td>{{ invoice.currency }}</td>
                <td>{{ invoice.total }}</td>
                <td>
                    <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                        <a href="{{ path('invoice.show', {'id': invoice.id}) }}" class="btn btn-primary">Show</a>
                        <a href="{{ path('invoice.edit', {'id': invoice.id}) }}" class="btn btn-warning">Edit</a>
                        <a href="{{ path('invoice.delete', {'id': invoice.id}) }}" class="btn btn-danger">Delete</a>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}