src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $tax_office;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $tax_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $id_no;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $bank;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $iban;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Invoice", mappedBy="user")
     */
    protected $invoices;

    public function __construct()
    {
        $this->invoices = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getTaxOffice(): ?string
    {
        return $this->tax_office;
    }

    public function setTaxOffice(string $tax_office): self
    {
        $this->tax_office = $tax_office;

        return $this;
    }

    public function getTaxId(): ?int
    {
        return $this->tax_id;
    }

    public function setTaxId(int $tax_id): self
    {
        $this->tax_id = $tax_id;

        return $this;
    }

    public function getIdNo(): ?string
    {
        return $this->id_no;
    }

    public function setIdNo(string $id_no): self
    {
        $this->id_no = $id_no;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getBank(): ?string
    {
        return $this->bank;
    }

    public function setBank(string $bank): self
    {
        $this->bank = $bank;

        return $this;
    }

    public function getIban(): ?string
    {
        return $this->iban;
    }

    public function setIban(string $iban): self
    {
        $this->iban = $iban;

        return $this;
    }

    public function getInvoices($invoiceNo)
    {
        return $this->invoices->filter(
            static function (Invoice $invoice) use ($invoiceNo) {
                return $invoiceNo === $invoice->getInvoiceNo();
            }
        );
    }

    public function setTriggers($invoices): self
    {
        $this->invoices = $invoices;

        return $this;
    }

    public function __toString()
    {
        return $this->name;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class)
            ->add('phone', TelType::class)
            ->add('email', EmailType::class)
            ->add('tax_office', TextType::class)
            ->add('tax_id', IntegerType::class)
            ->add('id_no', IntegerType::class)
            ->add('address', TextareaType::class)
            ->add('postal_code', IntegerType::class)
            ->add('bank', TextType::class)
            ->add('iban', TextType::class)
            ->add('submit', SubmitType::class);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            [
                'data_class' => User::class,
            ]
        );
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class UserController.
 *
 * @Route("/user")
 */
class UserController extends AbstractController
{
    /**
     * @var UserRepository
     */
    private $userRepository;

    public function __construct(UserRepository $userRepository)
    {
        $this->userRepository = $userRepository;
    }

    /**
     * @Route("", name="user.index", methods={"GET"})
     */
    public function index(): Response
    {
        $users = $this->userRepository->findAll();

        return $this->render(
            'user/index.html.twig',
            [
                'users' => $users,
            ]
        );
    }

    /**
     * @Route("/create", name="user.create")
     */
    public function create(Request $request): Response
    {
        $user = new User();
        $form = $this->createForm(
            UserType::class,
            $user,
            [
                'action' => $this->generateUrl('user.create'),
            ]
        );

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();
        }

        return $this->render(
            'user/create.html.twig',
            [
                'user_create_form' => $form->createView(),
            ]
        );
    }

    /**
     * @Route("/edit/{id}", name="user.edit")
     */
    public function edit(Request $request, $id): Response
    {
        $user = $this->userRepository->find($id);
        $form = $this->createForm(
            UserType::class,
            $user,
            [
                'action' => $this->generateUrl('user.edit', ['id' => $id]),
            ]
        );

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();
        }

        return $this->render(
            'user/create.html.twig',
            [
                'user_create_form' => $form->createView(),
            ]
        );
    }

    /**
     * @Route("/delete/{id}", name="user.delete")
     */
    public function delete($id): Response
    {
        $user = $this->userRepository->find($id);

        $em = $this->getDoctrine()->getManager();
        $em->remove($user);
        $em->flush();

        return $this->redirectToRoute('user.index');
    }

}

templates/user/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create User{% endblock %}
{% block body %}
    <a href="{{ path('user.index') }}" class="btn btn-primary">Back</a>

    {{ form_start(user_create_form, {'attr': {'id': 'create_user_form'}}) }}
    {{ form(user_create_form) }}
    {{ form_end(user_create_form) }}
{% endblock %}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create User{% endblock %}
{% block body %}
    <a href="{{ path('user.index') }}" class="btn btn-primary">Back</a>

    {{ form_start(user_create_form, {'attr': {'id': 'create_user_form'}}) }}
    {{ form(user_create_form) }}
    {{ form_end(user_create_form) }}
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello UserController!{% endblock %}

{% block body %}
    <a href="{{ path('user.create') }}" class="btn btn-primary">Create</a>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Phone</th>
            <th scope="col">Email</th>
            <th scope="col">Tax Office</th>
            <th scope="col">Tax ID</th>
            <th scope="col">ID No</th>
            <th scope="col">Address</th>
            <th scope="col">Postal Code</th>
            <th scope="col">Bank</th>
            <th scope="col">IBAN</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.name }}</td>
                <td>{{ user.phone }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.taxOffice }}</td>
                <td>{{ user.taxId }}</td>
                <td>{{ user.idNo }}</td>
                <td>{{ user.address }}</td>
                <td>{{ user.postalCode }}</td>
                <td>{{ user.bank }}</td>
                <td>{{ user.iban }}</td>
                <td>
                    <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                        <a href="{{ path('user.edit', {'id': user.id}) }}" class="btn btn-warning">Edit</a>
                        <a href="{{ path('user.delete', {'id': user.id}) }}" class="btn btn-danger">Delete</a>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}